[interpolators]
wl = "oimParamInterpolatorWl"
time = "oimParamInterpolatorTime"
GaussWl = "oimParamGaussianWl"
GaussTime = "oimParamGaussianTime"
mGaussWl = "oimParamMultipleGaussianWl"
mGaussTime = "oimParamMultipleGaussianTime"
cosTime = "oimParamCosineTime"
polyWl = "oimParamPolynomialWl"
polyTime = "oimParamPolynomialTime"
powerlawWl = "oimParamPowerLawWl"
powerlawTime = "oimParamPowerLawTime"
rangeWl = "oimParamLinearRangeWl"
templateWl = "oimParamLinearTemplateWl"
tempWl = "oimParamLinearTemperatureWl"
starWl = "oimParamLinearStarWl"
userFunc = "oimParamUserFunc"
